//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

package bloberror

import (
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated"
)

// BlobErrorCode - Error codes returned by the service
type BlobErrorCode = generated.StorageErrorCode

const (
	AccountAlreadyExists                              BlobErrorCode = "AccountAlreadyExists"
	AccountBeingCreated                               BlobErrorCode = "AccountBeingCreated"
	AccountIsDisabled                                 BlobErrorCode = "AccountIsDisabled"
	AppendPositionConditionNotMet                     BlobErrorCode = "AppendPositionConditionNotMet"
	AuthenticationFailed                              BlobErrorCode = "AuthenticationFailed"
	AuthorizationFailure                              BlobErrorCode = "AuthorizationFailure"
	AuthorizationPermissionMismatch                   BlobErrorCode = "AuthorizationPermissionMismatch"
	AuthorizationProtocolMismatch                     BlobErrorCode = "AuthorizationProtocolMismatch"
	AuthorizationResourceTypeMismatch                 BlobErrorCode = "AuthorizationResourceTypeMismatch"
	AuthorizationServiceMismatch                      BlobErrorCode = "AuthorizationServiceMismatch"
	AuthorizationSourceIPMismatch                     BlobErrorCode = "AuthorizationSourceIPMismatch"
	BlobAlreadyExists                                 BlobErrorCode = "BlobAlreadyExists"
	BlobArchived                                      BlobErrorCode = "BlobArchived"
	BlobBeingRehydrated                               BlobErrorCode = "BlobBeingRehydrated"
	BlobImmutableDueToPolicy                          BlobErrorCode = "BlobImmutableDueToPolicy"
	BlobNotArchived                                   BlobErrorCode = "BlobNotArchived"
	BlobNotFound                                      BlobErrorCode = "BlobNotFound"
	BlobOverwritten                                   BlobErrorCode = "BlobOverwritten"
	BlobTierInadequateForContentLength                BlobErrorCode = "BlobTierInadequateForContentLength"
	BlobUsesCustomerSpecifiedEncryption               BlobErrorCode = "BlobUsesCustomerSpecifiedEncryption"
	BlockCountExceedsLimit                            BlobErrorCode = "BlockCountExceedsLimit"
	BlockListTooLong                                  BlobErrorCode = "BlockListTooLong"
	CannotChangeToLowerTier                           BlobErrorCode = "CannotChangeToLowerTier"
	CannotVerifyCopySource                            BlobErrorCode = "CannotVerifyCopySource"
	ConditionHeadersNotSupported                      BlobErrorCode = "ConditionHeadersNotSupported"
	ConditionNotMet                                   BlobErrorCode = "ConditionNotMet"
	ContainerAlreadyExists                            BlobErrorCode = "ContainerAlreadyExists"
	ContainerBeingDeleted                             BlobErrorCode = "ContainerBeingDeleted"
	ContainerDisabled                                 BlobErrorCode = "ContainerDisabled"
	ContainerNotFound                                 BlobErrorCode = "ContainerNotFound"
	ContentLengthLargerThanTierLimit                  BlobErrorCode = "ContentLengthLargerThanTierLimit"
	CopyAcrossAccountsNotSupported                    BlobErrorCode = "CopyAcrossAccountsNotSupported"
	CopyIDMismatch                                    BlobErrorCode = "CopyIdMismatch"
	EmptyMetadataKey                                  BlobErrorCode = "EmptyMetadataKey"
	FeatureVersionMismatch                            BlobErrorCode = "FeatureVersionMismatch"
	IncrementalCopyBlobMismatch                       BlobErrorCode = "IncrementalCopyBlobMismatch"
	IncrementalCopyOfEralierVersionSnapshotNotAllowed BlobErrorCode = "IncrementalCopyOfEralierVersionSnapshotNotAllowed"
	IncrementalCopySourceMustBeSnapshot               BlobErrorCode = "IncrementalCopySourceMustBeSnapshot"
	InfiniteLeaseDurationRequired                     BlobErrorCode = "InfiniteLeaseDurationRequired"
	InsufficientAccountPermissions                    BlobErrorCode = "InsufficientAccountPermissions"
	InternalError                                     BlobErrorCode = "InternalError"
	InvalidAuthenticationInfo                         BlobErrorCode = "InvalidAuthenticationInfo"
	InvalidBlobOrBlock                                BlobErrorCode = "InvalidBlobOrBlock"
	InvalidBlobTier                                   BlobErrorCode = "InvalidBlobTier"
	InvalidBlobType                                   BlobErrorCode = "InvalidBlobType"
	InvalidBlockID                                    BlobErrorCode = "InvalidBlockId"
	InvalidBlockList                                  BlobErrorCode = "InvalidBlockList"
	InvalidHTTPVerb                                   BlobErrorCode = "InvalidHttpVerb"
	InvalidHeaderValue                                BlobErrorCode = "InvalidHeaderValue"
	InvalidInput                                      BlobErrorCode = "InvalidInput"
	InvalidMD5                                        BlobErrorCode = "InvalidMd5"
	InvalidMetadata                                   BlobErrorCode = "InvalidMetadata"
	InvalidOperation                                  BlobErrorCode = "InvalidOperation"
	InvalidPageRange                                  BlobErrorCode = "InvalidPageRange"
	InvalidQueryParameterValue                        BlobErrorCode = "InvalidQueryParameterValue"
	InvalidRange                                      BlobErrorCode = "InvalidRange"
	InvalidResourceName                               BlobErrorCode = "InvalidResourceName"
	InvalidSourceBlobType                             BlobErrorCode = "InvalidSourceBlobType"
	InvalidSourceBlobURL                              BlobErrorCode = "InvalidSourceBlobUrl"
	InvalidURI                                        BlobErrorCode = "InvalidUri"
	InvalidVersionForPageBlobOperation                BlobErrorCode = "InvalidVersionForPageBlobOperation"
	InvalidXMLDocument                                BlobErrorCode = "InvalidXmlDocument"
	InvalidXMLNodeValue                               BlobErrorCode = "InvalidXmlNodeValue"
	LeaseAlreadyBroken                                BlobErrorCode = "LeaseAlreadyBroken"
	LeaseAlreadyPresent                               BlobErrorCode = "LeaseAlreadyPresent"
	LeaseIDMismatchWithBlobOperation                  BlobErrorCode = "LeaseIdMismatchWithBlobOperation"
	LeaseIDMismatchWithContainerOperation             BlobErrorCode = "LeaseIdMismatchWithContainerOperation"
	LeaseIDMismatchWithLeaseOperation                 BlobErrorCode = "LeaseIdMismatchWithLeaseOperation"
	LeaseIDMissing                                    BlobErrorCode = "LeaseIdMissing"
	LeaseIsBreakingAndCannotBeAcquired                BlobErrorCode = "LeaseIsBreakingAndCannotBeAcquired"
	LeaseIsBreakingAndCannotBeChanged                 BlobErrorCode = "LeaseIsBreakingAndCannotBeChanged"
	LeaseIsBrokenAndCannotBeRenewed                   BlobErrorCode = "LeaseIsBrokenAndCannotBeRenewed"
	LeaseLost                                         BlobErrorCode = "LeaseLost"
	LeaseNotPresentWithBlobOperation                  BlobErrorCode = "LeaseNotPresentWithBlobOperation"
	LeaseNotPresentWithContainerOperation             BlobErrorCode = "LeaseNotPresentWithContainerOperation"
	LeaseNotPresentWithLeaseOperation                 BlobErrorCode = "LeaseNotPresentWithLeaseOperation"
	MD5Mismatch                                       BlobErrorCode = "Md5Mismatch"
	MaxBlobSizeConditionNotMet                        BlobErrorCode = "MaxBlobSizeConditionNotMet"
	MetadataTooLarge                                  BlobErrorCode = "MetadataTooLarge"
	MissingContentLengthHeader                        BlobErrorCode = "MissingContentLengthHeader"
	MissingRequiredHeader                             BlobErrorCode = "MissingRequiredHeader"
	MissingRequiredQueryParameter                     BlobErrorCode = "MissingRequiredQueryParameter"
	MissingRequiredXMLNode                            BlobErrorCode = "MissingRequiredXmlNode"
	MultipleConditionHeadersNotSupported              BlobErrorCode = "MultipleConditionHeadersNotSupported"
	NoAuthenticationInformation                       BlobErrorCode = "NoAuthenticationInformation"
	NoPendingCopyOperation                            BlobErrorCode = "NoPendingCopyOperation"
	OperationNotAllowedOnIncrementalCopyBlob          BlobErrorCode = "OperationNotAllowedOnIncrementalCopyBlob"
	OperationTimedOut                                 BlobErrorCode = "OperationTimedOut"
	OutOfRangeInput                                   BlobErrorCode = "OutOfRangeInput"
	OutOfRangeQueryParameterValue                     BlobErrorCode = "OutOfRangeQueryParameterValue"
	PendingCopyOperation                              BlobErrorCode = "PendingCopyOperation"
	PreviousSnapshotCannotBeNewer                     BlobErrorCode = "PreviousSnapshotCannotBeNewer"
	PreviousSnapshotNotFound                          BlobErrorCode = "PreviousSnapshotNotFound"
	PreviousSnapshotOperationNotSupported             BlobErrorCode = "PreviousSnapshotOperationNotSupported"
	RequestBodyTooLarge                               BlobErrorCode = "RequestBodyTooLarge"
	RequestURLFailedToParse                           BlobErrorCode = "RequestUrlFailedToParse"
	ResourceAlreadyExists                             BlobErrorCode = "ResourceAlreadyExists"
	ResourceNotFound                                  BlobErrorCode = "ResourceNotFound"
	ResourceTypeMismatch                              BlobErrorCode = "ResourceTypeMismatch"
	SequenceNumberConditionNotMet                     BlobErrorCode = "SequenceNumberConditionNotMet"
	SequenceNumberIncrementTooLarge                   BlobErrorCode = "SequenceNumberIncrementTooLarge"
	ServerBusy                                        BlobErrorCode = "ServerBusy"
	SnapshotCountExceeded                             BlobErrorCode = "SnapshotCountExceeded"
	SnapshotOperationRateExceeded                     BlobErrorCode = "SnapshotOperationRateExceeded"
	SnapshotsPresent                                  BlobErrorCode = "SnapshotsPresent"
	SourceConditionNotMet                             BlobErrorCode = "SourceConditionNotMet"
	SystemInUse                                       BlobErrorCode = "SystemInUse"
	TargetConditionNotMet                             BlobErrorCode = "TargetConditionNotMet"
	UnauthorizedBlobOverwrite                         BlobErrorCode = "UnauthorizedBlobOverwrite"
	UnsupportedHTTPVerb                               BlobErrorCode = "UnsupportedHttpVerb"
	UnsupportedHeader                                 BlobErrorCode = "UnsupportedHeader"
	UnsupportedQueryParameter                         BlobErrorCode = "UnsupportedQueryParameter"
	UnsupportedXMLNode                                BlobErrorCode = "UnsupportedXmlNode"
)
