// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armsecurity

// UnmarshalJSON implements the json.Unmarshaller interface for type ExternalSecuritySolutionsClientGetResponse.
func (e *ExternalSecuritySolutionsClientGetResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalExternalSecuritySolutionClassification(data)
	if err != nil {
		return err
	}
	e.ExternalSecuritySolutionClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type ServerVulnerabilityAssessmentsSettingsClientCreateOrUpdateResponse.
func (s *ServerVulnerabilityAssessmentsSettingsClientCreateOrUpdateResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalServerVulnerabilityAssessmentsSettingClassification(data)
	if err != nil {
		return err
	}
	s.ServerVulnerabilityAssessmentsSettingClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type ServerVulnerabilityAssessmentsSettingsClientGetResponse.
func (s *ServerVulnerabilityAssessmentsSettingsClientGetResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalServerVulnerabilityAssessmentsSettingClassification(data)
	if err != nil {
		return err
	}
	s.ServerVulnerabilityAssessmentsSettingClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SettingsClientGetResponse.
func (s *SettingsClientGetResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalSettingClassification(data)
	if err != nil {
		return err
	}
	s.SettingClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type SettingsClientUpdateResponse.
func (s *SettingsClientUpdateResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalSettingClassification(data)
	if err != nil {
		return err
	}
	s.SettingClassification = res
	return nil
}
