// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

package link

const (
	// SpecOwner ...
	SpecOwner = "Azure"
	// SpecRepo ...
	SpecRepo = "azure-rest-api-specs"
	// SpecRepoPrefix ...
	SpecRepoPrefix = "https://github.com/Azure/azure-rest-api-specs/"
	// PullRequestPrefix ...
	PullRequestPrefix = "pull/"
	// DirectoryPrefix ...
	DirectoryPrefix = "tree/"
	// FilePrefix ...
	FilePrefix = "blob/"
	// CommitPrefix ...
	CommitPrefix = "commit/"
	// SDKRepo ...
	SDKRepo = "azure-sdk-for-go"
	// ReleaseIssueRepo SDK Release Request Repo ...
	ReleaseIssueRepo = "sdk-release-request"
)
