// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armplaceholder

// ArtifactsClientGetOptions contains the optional parameters for the ArtifactsClient.Get method.
type ArtifactsClientGetOptions struct {
	// placeholder for future optional parameters
}

// ArtifactsClientListByParentOptions contains the optional parameters for the ArtifactsClient.NewListByParentPager method.
type ArtifactsClientListByParentOptions struct {
	// placeholder for future optional parameters
}

// ArtifactsClientListDownloadURIOptions contains the optional parameters for the ArtifactsClient.ListDownloadURI method.
type ArtifactsClientListDownloadURIOptions struct {
	// placeholder for future optional parameters
}

// DisconnectedOperationsClientBeginCreateOrUpdateOptions contains the optional parameters for the DisconnectedOperationsClient.BeginCreateOrUpdate
// method.
type DisconnectedOperationsClientBeginCreateOrUpdateOptions struct {
	// Resumes the long-running operation from the provided token.
	ResumeToken string
}

// DisconnectedOperationsClientBeginDeleteOptions contains the optional parameters for the DisconnectedOperationsClient.BeginDelete
// method.
type DisconnectedOperationsClientBeginDeleteOptions struct {
	// Resumes the long-running operation from the provided token.
	ResumeToken string
}

// DisconnectedOperationsClientGetOptions contains the optional parameters for the DisconnectedOperationsClient.Get method.
type DisconnectedOperationsClientGetOptions struct {
	// placeholder for future optional parameters
}

// DisconnectedOperationsClientListByResourceGroupOptions contains the optional parameters for the DisconnectedOperationsClient.NewListByResourceGroupPager
// method.
type DisconnectedOperationsClientListByResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// DisconnectedOperationsClientListBySubscriptionOptions contains the optional parameters for the DisconnectedOperationsClient.NewListBySubscriptionPager
// method.
type DisconnectedOperationsClientListBySubscriptionOptions struct {
	// placeholder for future optional parameters
}

// DisconnectedOperationsClientListDeploymentManifestOptions contains the optional parameters for the DisconnectedOperationsClient.ListDeploymentManifest
// method.
type DisconnectedOperationsClientListDeploymentManifestOptions struct {
	// placeholder for future optional parameters
}

// DisconnectedOperationsClientUpdateOptions contains the optional parameters for the DisconnectedOperationsClient.Update
// method.
type DisconnectedOperationsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// ImagesClientGetOptions contains the optional parameters for the ImagesClient.Get method.
type ImagesClientGetOptions struct {
	// placeholder for future optional parameters
}

// ImagesClientListByDisconnectedOperationOptions contains the optional parameters for the ImagesClient.NewListByDisconnectedOperationPager
// method.
type ImagesClientListByDisconnectedOperationOptions struct {
	// Filter the result list using the given expression.
	Filter *string

	// The number of result items to skip.
	Skip *int32

	// The number of result items to return.
	Top *int32
}

// ImagesClientListDownloadURIOptions contains the optional parameters for the ImagesClient.ListDownloadURI method.
type ImagesClientListDownloadURIOptions struct {
	// placeholder for future optional parameters
}
