package link

const (
	// SpecOwner ...
	SpecOwner = "Azure"
	// SpecRepo ...
	SpecRepo = "azure-rest-api-specs"
	// SpecRepoPrefix ...
	SpecRepoPrefix = "https://github.com/Azure/azure-rest-api-specs/"
	// PullRequestPrefix ...
	PullRequestPrefix = "pull/"
	// DirectoryPrefix ...
	DirectoryPrefix = "tree/"
	// FilePrefix ...
	FilePrefix = "blob/"
	// CommitPrefix ...
	CommitPrefix = "commit/"
)
