// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator.

package armcontoso

const (
	moduleName    = "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/contoso/armcontoso"
	moduleVersion = "v0.1.0"
)
