trigger: none
pr: none

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
      - stage:
        variables:
          - template: /eng/pipelines/templates/variables/image.yml
        jobs:
          - job:
            variables:
              autoReleaseNpmrcPath: $(Agent.TempDirectory)/mgmt-auto-release/.npmrc

            pool:
              image: $(LINUXVMIMAGE)
              name: $(LINUXPOOL)
              os: linux


            displayName: Go Auto Release
            steps:
              - template: /eng/common/pipelines/templates/steps/create-authenticated-npmrc.yml
                parameters:
                  npmrcPath: $(autoReleaseNpmrcPath)

              - task: Npm@1
                inputs:
                  command: 'custom'
                  customCommand: 'install -g autorest@latest'
                env:
                  npm_config_userconfig: $(autoReleaseNpmrcPath)

              - task: Npm@1
                inputs:
                  command: 'ci'
                  workingDir: 'eng/common/tsp-client'
                env:
                  npm_config_userconfig: $(autoReleaseNpmrcPath)

              - task: GoTool@0
                inputs:
                  version: '1.25.4'

              - template: /eng/common/pipelines/templates/steps/login-to-github.yml
                parameters:
                  TokenOwners:
                    - azure

              - task: ShellScript@2
                inputs:
                  scriptPath: 'eng/scripts/mgmt-auto-release.sh'
                  cwd: '$(System.DefaultWorkingDirectory)'
                env:
                  GH_TOKEN: $(GH_TOKEN)
