// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armmonitor

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"net/http"
	"net/url"
	"strings"
)

// ActivityLogsOperations contains the methods for the ActivityLogs group.
type ActivityLogsOperations interface {
	// List - Provides the list of records from the activity logs.
	List(filter string, options *ActivityLogsListOptions) EventDataCollectionPager
}

// ActivityLogsClient implements the ActivityLogsOperations interface.
// Don't use this type directly, use NewActivityLogsClient() instead.
type ActivityLogsClient struct {
	*Client
	subscriptionID string
}

// NewActivityLogsClient creates a new instance of ActivityLogsClient with the specified values.
func NewActivityLogsClient(c *Client, subscriptionID string) ActivityLogsOperations {
	return &ActivityLogsClient{Client: c, subscriptionID: subscriptionID}
}

// Do invokes the Do() method on the pipeline associated with this client.
func (client *ActivityLogsClient) Do(req *azcore.Request) (*azcore.Response, error) {
	return client.p.Do(req)
}

// List - Provides the list of records from the activity logs.
func (client *ActivityLogsClient) List(filter string, options *ActivityLogsListOptions) EventDataCollectionPager {
	return &eventDataCollectionPager{
		pipeline: client.p,
		requester: func(ctx context.Context) (*azcore.Request, error) {
			return client.ListCreateRequest(ctx, filter, options)
		},
		responder: client.ListHandleResponse,
		errorer:   client.ListHandleError,
		advancer: func(ctx context.Context, resp *EventDataCollectionResponse) (*azcore.Request, error) {
			return azcore.NewRequest(ctx, http.MethodGet, *resp.EventDataCollection.NextLink)
		},
		statusCodes: []int{http.StatusOK},
	}
}

// ListCreateRequest creates the List request.
func (client *ActivityLogsClient) ListCreateRequest(ctx context.Context, filter string, options *ActivityLogsListOptions) (*azcore.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/providers/microsoft.insights/eventtypes/management/values"
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	req, err := azcore.NewRequest(ctx, http.MethodGet, azcore.JoinPaths(client.u, urlPath))
	if err != nil {
		return nil, err
	}
	query := req.URL.Query()
	query.Set("api-version", "2015-04-01")
	query.Set("$filter", filter)
	if options != nil && options.SelectParameter != nil {
		query.Set("$select", *options.SelectParameter)
	}
	req.URL.RawQuery = query.Encode()
	req.Header.Set("Accept", "application/json")
	return req, nil
}

// ListHandleResponse handles the List response.
func (client *ActivityLogsClient) ListHandleResponse(resp *azcore.Response) (*EventDataCollectionResponse, error) {
	result := EventDataCollectionResponse{RawResponse: resp.Response}
	return &result, resp.UnmarshalAsJSON(&result.EventDataCollection)
}

// ListHandleError handles the List error response.
func (client *ActivityLogsClient) ListHandleError(resp *azcore.Response) error {
	var err ErrorResponse
	if err := resp.UnmarshalAsJSON(&err); err != nil {
		return err
	}
	return azcore.NewResponseError(&err, resp.Response)
}
