//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

package systemevents

// Type represents the value set in EventData.EventType or messaging.CloudEvent.Type
// for system events.
type Type string

const (
	TypeAPIManagementAPICreatedEventData                          Type = "Microsoft.ApiManagement.APICreated"                                // maps to APIManagementAPICreatedEventData
	TypeAPIManagementAPIDeletedEventData                          Type = "Microsoft.ApiManagement.APIDeleted"                                // maps to APIManagementAPIDeletedEventData
	TypeAPIManagementAPIReleaseCreatedEventData                   Type = "Microsoft.ApiManagement.APIReleaseCreated"                         // maps to APIManagementAPIReleaseCreatedEventData
	TypeAPIManagementAPIReleaseDeletedEventData                   Type = "Microsoft.ApiManagement.APIReleaseDeleted"                         // maps to APIManagementAPIReleaseDeletedEventData
	TypeAPIManagementAPIReleaseUpdatedEventData                   Type = "Microsoft.ApiManagement.APIReleaseUpdated"                         // maps to APIManagementAPIReleaseUpdatedEventData
	TypeAPIManagementAPIUpdatedEventData                          Type = "Microsoft.ApiManagement.APIUpdated"                                // maps to APIManagementAPIUpdatedEventData
	TypeAPIManagementGatewayAPIAddedEventData                     Type = "Microsoft.ApiManagement.GatewayAPIAdded"                           // maps to APIManagementGatewayAPIAddedEventData
	TypeAPIManagementGatewayAPIRemovedEventData                   Type = "Microsoft.ApiManagement.GatewayAPIRemoved"                         // maps to APIManagementGatewayAPIRemovedEventData
	TypeAPIManagementGatewayCertificateAuthorityCreatedEventData  Type = "Microsoft.ApiManagement.GatewayCertificateAuthorityCreated"        // maps to APIManagementGatewayCertificateAuthorityCreatedEventData
	TypeAPIManagementGatewayCertificateAuthorityDeletedEventData  Type = "Microsoft.ApiManagement.GatewayCertificateAuthorityDeleted"        // maps to APIManagementGatewayCertificateAuthorityDeletedEventData
	TypeAPIManagementGatewayCertificateAuthorityUpdatedEventData  Type = "Microsoft.ApiManagement.GatewayCertificateAuthorityUpdated"        // maps to APIManagementGatewayCertificateAuthorityUpdatedEventData
	TypeAPIManagementGatewayCreatedEventData                      Type = "Microsoft.ApiManagement.GatewayCreated"                            // maps to APIManagementGatewayCreatedEventData
	TypeAPIManagementGatewayDeletedEventData                      Type = "Microsoft.ApiManagement.GatewayDeleted"                            // maps to APIManagementGatewayDeletedEventData
	TypeAPIManagementGatewayHostnameConfigurationCreatedEventData Type = "Microsoft.ApiManagement.GatewayHostnameConfigurationCreated"       // maps to APIManagementGatewayHostnameConfigurationCreatedEventData
	TypeAPIManagementGatewayHostnameConfigurationDeletedEventData Type = "Microsoft.ApiManagement.GatewayHostnameConfigurationDeleted"       // maps to APIManagementGatewayHostnameConfigurationDeletedEventData
	TypeAPIManagementGatewayHostnameConfigurationUpdatedEventData Type = "Microsoft.ApiManagement.GatewayHostnameConfigurationUpdated"       // maps to APIManagementGatewayHostnameConfigurationUpdatedEventData
	TypeAPIManagementGatewayUpdatedEventData                      Type = "Microsoft.ApiManagement.GatewayUpdated"                            // maps to APIManagementGatewayUpdatedEventData
	TypeAPIManagementProductCreatedEventData                      Type = "Microsoft.ApiManagement.ProductCreated"                            // maps to APIManagementProductCreatedEventData
	TypeAPIManagementProductDeletedEventData                      Type = "Microsoft.ApiManagement.ProductDeleted"                            // maps to APIManagementProductDeletedEventData
	TypeAPIManagementProductUpdatedEventData                      Type = "Microsoft.ApiManagement.ProductUpdated"                            // maps to APIManagementProductUpdatedEventData
	TypeAPIManagementSubscriptionCreatedEventData                 Type = "Microsoft.ApiManagement.SubscriptionCreated"                       // maps to APIManagementSubscriptionCreatedEventData
	TypeAPIManagementSubscriptionDeletedEventData                 Type = "Microsoft.ApiManagement.SubscriptionDeleted"                       // maps to APIManagementSubscriptionDeletedEventData
	TypeAPIManagementSubscriptionUpdatedEventData                 Type = "Microsoft.ApiManagement.SubscriptionUpdated"                       // maps to APIManagementSubscriptionUpdatedEventData
	TypeAPIManagementUserCreatedEventData                         Type = "Microsoft.ApiManagement.UserCreated"                               // maps to APIManagementUserCreatedEventData
	TypeAPIManagementUserDeletedEventData                         Type = "Microsoft.ApiManagement.UserDeleted"                               // maps to APIManagementUserDeletedEventData
	TypeAPIManagementUserUpdatedEventData                         Type = "Microsoft.ApiManagement.UserUpdated"                               // maps to APIManagementUserUpdatedEventData
	TypeAcsChatMessageDeletedEventData                            Type = "Microsoft.Communication.ChatMessageDeleted"                        // maps to AcsChatMessageDeletedEventData
	TypeAcsChatMessageDeletedInThreadEventData                    Type = "Microsoft.Communication.ChatMessageDeletedInThread"                // maps to AcsChatMessageDeletedInThreadEventData
	TypeAcsChatMessageEditedEventData                             Type = "Microsoft.Communication.ChatMessageEdited"                         // maps to AcsChatMessageEditedEventData
	TypeAcsChatMessageEditedInThreadEventData                     Type = "Microsoft.Communication.ChatMessageEditedInThread"                 // maps to AcsChatMessageEditedInThreadEventData
	TypeAcsChatMessageReceivedEventData                           Type = "Microsoft.Communication.ChatMessageReceived"                       // maps to AcsChatMessageReceivedEventData
	TypeAcsChatMessageReceivedInThreadEventData                   Type = "Microsoft.Communication.ChatMessageReceivedInThread"               // maps to AcsChatMessageReceivedInThreadEventData
	TypeAcsChatParticipantAddedToThreadEventData                  Type = "Microsoft.Communication.ChatThreadParticipantAdded"                // maps to AcsChatParticipantAddedToThreadEventData
	TypeAcsChatParticipantAddedToThreadWithUserEventData          Type = "Microsoft.Communication.ChatParticipantAddedToThreadWithUser"      // maps to AcsChatParticipantAddedToThreadWithUserEventData
	TypeAcsChatParticipantRemovedFromThreadEventData              Type = "Microsoft.Communication.ChatThreadParticipantRemoved"              // maps to AcsChatParticipantRemovedFromThreadEventData
	TypeAcsChatParticipantRemovedFromThreadWithUserEventData      Type = "Microsoft.Communication.ChatParticipantRemovedFromThreadWithUser"  // maps to AcsChatParticipantRemovedFromThreadWithUserEventData
	TypeAcsChatThreadCreatedEventData                             Type = "Microsoft.Communication.ChatThreadCreated"                         // maps to AcsChatThreadCreatedEventData
	TypeAcsChatThreadCreatedWithUserEventData                     Type = "Microsoft.Communication.ChatThreadCreatedWithUser"                 // maps to AcsChatThreadCreatedWithUserEventData
	TypeAcsChatThreadDeletedEventData                             Type = "Microsoft.Communication.ChatThreadDeleted"                         // maps to AcsChatThreadDeletedEventData
	TypeAcsChatThreadPropertiesUpdatedEventData                   Type = "Microsoft.Communication.ChatThreadPropertiesUpdated"               // maps to AcsChatThreadPropertiesUpdatedEventData
	TypeAcsChatThreadPropertiesUpdatedPerUserEventData            Type = "Microsoft.Communication.ChatThreadPropertiesUpdatedPerUser"        // maps to AcsChatThreadPropertiesUpdatedPerUserEventData
	TypeAcsChatThreadWithUserDeletedEventData                     Type = "Microsoft.Communication.ChatThreadWithUserDeleted"                 // maps to AcsChatThreadWithUserDeletedEventData
	TypeAcsEmailDeliveryReportReceivedEventData                   Type = "Microsoft.Communication.EmailDeliveryReportReceived"               // maps to AcsEmailDeliveryReportReceivedEventData
	TypeAcsEmailEngagementTrackingReportReceivedEventData         Type = "Microsoft.Communication.EmailEngagementTrackingReportReceived"     // maps to AcsEmailEngagementTrackingReportReceivedEventData
	TypeAcsRecordingFileStatusUpdatedEventData                    Type = "Microsoft.Communication.RecordingFileStatusUpdated"                // maps to AcsRecordingFileStatusUpdatedEventData
	TypeAcsRouterJobCancelledEventData                            Type = "Microsoft.Communication.RouterJobCancelled"                        // maps to AcsRouterJobCancelledEventData
	TypeAcsRouterJobClassificationFailedEventData                 Type = "Microsoft.Communication.RouterJobClassificationFailed"             // maps to AcsRouterJobClassificationFailedEventData
	TypeAcsRouterJobClassifiedEventData                           Type = "Microsoft.Communication.RouterJobClassified"                       // maps to AcsRouterJobClassifiedEventData
	TypeAcsRouterJobClosedEventData                               Type = "Microsoft.Communication.RouterJobClosed"                           // maps to AcsRouterJobClosedEventData
	TypeAcsRouterJobCompletedEventData                            Type = "Microsoft.Communication.RouterJobCompleted"                        // maps to AcsRouterJobCompletedEventData
	TypeAcsRouterJobDeletedEventData                              Type = "Microsoft.Communication.RouterJobDeleted"                          // maps to AcsRouterJobDeletedEventData
	TypeAcsRouterJobExceptionTriggeredEventData                   Type = "Microsoft.Communication.RouterJobExceptionTriggered"               // maps to AcsRouterJobExceptionTriggeredEventData
	TypeAcsRouterJobQueuedEventData                               Type = "Microsoft.Communication.RouterJobQueued"                           // maps to AcsRouterJobQueuedEventData
	TypeAcsRouterJobReceivedEventData                             Type = "Microsoft.Communication.RouterJobReceived"                         // maps to AcsRouterJobReceivedEventData
	TypeAcsRouterJobSchedulingFailedEventData                     Type = "Microsoft.Communication.RouterJobSchedulingFailed"                 // maps to AcsRouterJobSchedulingFailedEventData
	TypeAcsRouterJobUnassignedEventData                           Type = "Microsoft.Communication.RouterJobUnassigned"                       // maps to AcsRouterJobUnassignedEventData
	TypeAcsRouterJobWaitingForActivationEventData                 Type = "Microsoft.Communication.RouterJobWaitingForActivation"             // maps to AcsRouterJobWaitingForActivationEventData
	TypeAcsRouterJobWorkerSelectorsExpiredEventData               Type = "Microsoft.Communication.RouterJobWorkerSelectorsExpired"           // maps to AcsRouterJobWorkerSelectorsExpiredEventData
	TypeAcsRouterWorkerDeletedEventData                           Type = "Microsoft.Communication.RouterWorkerDeleted"                       // maps to AcsRouterWorkerDeletedEventData
	TypeAcsRouterWorkerDeregisteredEventData                      Type = "Microsoft.Communication.RouterWorkerDeregistered"                  // maps to AcsRouterWorkerDeregisteredEventData
	TypeAcsRouterWorkerOfferAcceptedEventData                     Type = "Microsoft.Communication.RouterWorkerOfferAccepted"                 // maps to AcsRouterWorkerOfferAcceptedEventData
	TypeAcsRouterWorkerOfferDeclinedEventData                     Type = "Microsoft.Communication.RouterWorkerOfferDeclined"                 // maps to AcsRouterWorkerOfferDeclinedEventData
	TypeAcsRouterWorkerOfferExpiredEventData                      Type = "Microsoft.Communication.RouterWorkerOfferExpired"                  // maps to AcsRouterWorkerOfferExpiredEventData
	TypeAcsRouterWorkerOfferIssuedEventData                       Type = "Microsoft.Communication.RouterWorkerOfferIssued"                   // maps to AcsRouterWorkerOfferIssuedEventData
	TypeAcsRouterWorkerOfferRevokedEventData                      Type = "Microsoft.Communication.RouterWorkerOfferRevoked"                  // maps to AcsRouterWorkerOfferRevokedEventData
	TypeAcsRouterWorkerRegisteredEventData                        Type = "Microsoft.Communication.RouterWorkerRegistered"                    // maps to AcsRouterWorkerRegisteredEventData
	TypeAcsSmsDeliveryReportReceivedEventData                     Type = "Microsoft.Communication.SMSDeliveryReportReceived"                 // maps to AcsSmsDeliveryReportReceivedEventData
	TypeAcsSmsReceivedEventData                                   Type = "Microsoft.Communication.SMSReceived event."                        // maps to AcsSmsReceivedEventData
	TypeAppConfigurationKeyValueDeletedEventData                  Type = "Microsoft.AppConfiguration.KeyValueDeleted"                        // maps to AppConfigurationKeyValueDeletedEventData
	TypeAppConfigurationKeyValueModifiedEventData                 Type = "Microsoft.AppConfiguration.KeyValueModified"                       // maps to AppConfigurationKeyValueModifiedEventData
	TypeAppConfigurationSnapshotCreatedEventData                  Type = "Microsoft.AppConfiguration.SnapshotCreated"                        // maps to AppConfigurationSnapshotCreatedEventData
	TypeAppConfigurationSnapshotModifiedEventData                 Type = "Microsoft.AppConfiguration.SnapshotModified"                       // maps to AppConfigurationSnapshotModifiedEventData
	TypeContainerRegistryChartDeletedEventData                    Type = "Microsoft.ContainerRegistry.ChartDeleted"                          // maps to ContainerRegistryChartDeletedEventData
	TypeContainerRegistryChartPushedEventData                     Type = "Microsoft.ContainerRegistry.ChartPushed"                           // maps to ContainerRegistryChartPushedEventData
	TypeContainerRegistryImageDeletedEventData                    Type = "Microsoft.ContainerRegistry.ImageDeleted"                          // maps to ContainerRegistryImageDeletedEventData
	TypeContainerRegistryImagePushedEventData                     Type = "Microsoft.ContainerRegistry.ImagePushed"                           // maps to ContainerRegistryImagePushedEventData
	TypeContainerServiceClusterSupportEndedEventData              Type = "Microsoft.ContainerService.ClusterSupportEnded"                    // maps to ContainerServiceClusterSupportEndedEventData
	TypeContainerServiceClusterSupportEndingEventData             Type = "Microsoft.ContainerService.ClusterSupportEnding"                   // maps to ContainerServiceClusterSupportEndingEventData
	TypeContainerServiceNewKubernetesVersionAvailableEventData    Type = "Microsoft.ContainerService.NewKubernetesVersionAvailable"          // maps to ContainerServiceNewKubernetesVersionAvailableEventData
	TypeContainerServiceNodePoolRollingFailedEventData            Type = "Microsoft.ContainerService.NodePoolRollingFailed"                  // maps to ContainerServiceNodePoolRollingFailedEventData
	TypeContainerServiceNodePoolRollingStartedEventData           Type = "Microsoft.ContainerService.NodePoolRollingStarted"                 // maps to ContainerServiceNodePoolRollingStartedEventData
	TypeContainerServiceNodePoolRollingSucceededEventData         Type = "Microsoft.ContainerService.NodePoolRollingSucceeded"               // maps to ContainerServiceNodePoolRollingSucceededEventData
	TypeDataBoxCopyCompletedEventData                             Type = "Microsoft.DataBox.CopyCompleted"                                   // maps to DataBoxCopyCompletedEventData
	TypeDataBoxCopyStartedEventData                               Type = "Microsoft.DataBox.CopyStarted event."                              // maps to DataBoxCopyStartedEventData
	TypeDataBoxOrderCompletedEventData                            Type = "Microsoft.DataBox.OrderCompleted"                                  // maps to DataBoxOrderCompletedEventData
	TypeDeviceConnectionStateEventProperties                      Type = "device connection state event"                                     // maps to DeviceConnectionStateEventProperties
	TypeDeviceLifeCycleEventProperties                            Type = "device life cycle event (DeviceCreated,"                           // maps to DeviceLifeCycleEventProperties
	TypeDeviceTelemetryEventProperties                            Type = "device telemetry event (DeviceTelemetry)."                         // maps to DeviceTelemetryEventProperties
	TypeEventHubCaptureFileCreatedEventData                       Type = "Microsoft.EventHub.CaptureFileCreated"                             // maps to EventHubCaptureFileCreatedEventData
	TypeHealthcareDicomImageCreatedEventData                      Type = "Microsoft.HealthcareApis.DicomImageCreated"                        // maps to HealthcareDicomImageCreatedEventData
	TypeHealthcareDicomImageDeletedEventData                      Type = "Microsoft.HealthcareApis.DicomImageDeleted"                        // maps to HealthcareDicomImageDeletedEventData
	TypeHealthcareDicomImageUpdatedEventData                      Type = "Microsoft.HealthcareApis.DicomImageUpdated"                        // maps to HealthcareDicomImageUpdatedEventData
	TypeHealthcareFhirResourceCreatedEventData                    Type = "Microsoft.HealthcareApis.FhirResourceCreated"                      // maps to HealthcareFhirResourceCreatedEventData
	TypeHealthcareFhirResourceDeletedEventData                    Type = "Microsoft.HealthcareApis.FhirResourceDeleted"                      // maps to HealthcareFhirResourceDeletedEventData
	TypeHealthcareFhirResourceUpdatedEventData                    Type = "Microsoft.HealthcareApis.FhirResourceUpdated"                      // maps to HealthcareFhirResourceUpdatedEventData
	TypeKeyVaultAccessPolicyChangedEventData                      Type = "Microsoft.KeyVault.VaultAccessPolicyChanged"                       // maps to KeyVaultAccessPolicyChangedEventData
	TypeKeyVaultCertificateExpiredEventData                       Type = "Microsoft.KeyVault.CertificateExpired"                             // maps to KeyVaultCertificateExpiredEventData
	TypeKeyVaultCertificateNearExpiryEventData                    Type = "Microsoft.KeyVault.CertificateNearExpiry"                          // maps to KeyVaultCertificateNearExpiryEventData
	TypeKeyVaultCertificateNewVersionCreatedEventData             Type = "Microsoft.KeyVault.CertificateNewVersionCreated"                   // maps to KeyVaultCertificateNewVersionCreatedEventData
	TypeKeyVaultKeyExpiredEventData                               Type = "Microsoft.KeyVault.KeyExpired event."                              // maps to KeyVaultKeyExpiredEventData
	TypeKeyVaultKeyNearExpiryEventData                            Type = "Microsoft.KeyVault.KeyNearExpiry"                                  // maps to KeyVaultKeyNearExpiryEventData
	TypeKeyVaultKeyNewVersionCreatedEventData                     Type = "Microsoft.KeyVault.KeyNewVersionCreated"                           // maps to KeyVaultKeyNewVersionCreatedEventData
	TypeKeyVaultSecretExpiredEventData                            Type = "Microsoft.KeyVault.SecretExpired"                                  // maps to KeyVaultSecretExpiredEventData
	TypeKeyVaultSecretNearExpiryEventData                         Type = "Microsoft.KeyVault.SecretNearExpiry"                               // maps to KeyVaultSecretNearExpiryEventData
	TypeKeyVaultSecretNewVersionCreatedEventData                  Type = "Microsoft.KeyVault.SecretNewVersionCreated"                        // maps to KeyVaultSecretNewVersionCreatedEventData
	TypeMachineLearningServicesDatasetDriftDetectedEventData      Type = "Microsoft.MachineLearningServices.DatasetDriftDetected"            // maps to MachineLearningServicesDatasetDriftDetectedEventData
	TypeMachineLearningServicesModelDeployedEventData             Type = "Microsoft.MachineLearningServices.ModelDeployed"                   // maps to MachineLearningServicesModelDeployedEventData
	TypeMachineLearningServicesModelRegisteredEventData           Type = "Microsoft.MachineLearningServices.ModelRegistered"                 // maps to MachineLearningServicesModelRegisteredEventData
	TypeMachineLearningServicesRunCompletedEventData              Type = "Microsoft.MachineLearningServices.RunCompleted"                    // maps to MachineLearningServicesRunCompletedEventData
	TypeMachineLearningServicesRunStatusChangedEventData          Type = "Microsoft.MachineLearningServices.RunStatusChanged"                // maps to MachineLearningServicesRunStatusChangedEventData
	TypeMapsGeofenceEnteredEventData                              Type = "Microsoft.Maps.GeofenceEntered event."                             // maps to MapsGeofenceEnteredEventData
	TypeMapsGeofenceEventProperties                               Type = "Geofence event (GeofenceEntered, GeofenceExited,"                  // maps to MapsGeofenceEventProperties
	TypeMapsGeofenceExitedEventData                               Type = "Microsoft.Maps.GeofenceExited event."                              // maps to MapsGeofenceExitedEventData
	TypeMapsGeofenceResultEventData                               Type = "Microsoft.Maps.GeofenceResult event."                              // maps to MapsGeofenceResultEventData
	TypeMediaJobOutputStateChangeEventData                        Type = "Microsoft.Media.JobOutputStateChange"                              // maps to MediaJobOutputStateChangeEventData
	TypeMediaJobStateChangeEventData                              Type = "Microsoft.Media.JobStateChange event."                             // maps to MediaJobStateChangeEventData
	TypePolicyInsightsPolicyStateChangedEventData                 Type = "Microsoft.PolicyInsights.PolicyStateChanged"                       // maps to PolicyInsightsPolicyStateChangedEventData
	TypePolicyInsightsPolicyStateCreatedEventData                 Type = "Microsoft.PolicyInsights.PolicyStateCreated"                       // maps to PolicyInsightsPolicyStateCreatedEventData
	TypePolicyInsightsPolicyStateDeletedEventData                 Type = "Microsoft.PolicyInsights.PolicyStateDeleted"                       // maps to PolicyInsightsPolicyStateDeletedEventData
	TypeRedisExportRDBCompletedEventData                          Type = "Microsoft.Cache.ExportRDBCompleted"                                // maps to RedisExportRDBCompletedEventData
	TypeRedisImportRDBCompletedEventData                          Type = "Microsoft.Cache.ImportRDBCompleted"                                // maps to RedisImportRDBCompletedEventData
	TypeRedisPatchingCompletedEventData                           Type = "Microsoft.Cache.PatchingCompleted"                                 // maps to RedisPatchingCompletedEventData
	TypeRedisScalingCompletedEventData                            Type = "Microsoft.Cache.ScalingCompleted"                                  // maps to RedisScalingCompletedEventData
	TypeResourceActionCancelEventData                             Type = "Microsoft.Resources.ResourceActionCancel"                          // maps to ResourceActionCancelEventData
	TypeResourceActionFailureEventData                            Type = "Microsoft.Resources.ResourceActionFailure"                         // maps to ResourceActionFailureEventData
	TypeResourceActionSuccessEventData                            Type = "Microsoft.Resources.ResourceActionSuccess"                         // maps to ResourceActionSuccessEventData
	TypeResourceDeleteCancelEventData                             Type = "Microsoft.Resources.ResourceDeleteCancel"                          // maps to ResourceDeleteCancelEventData
	TypeResourceDeleteFailureEventData                            Type = "Microsoft.Resources.ResourceDeleteFailure"                         // maps to ResourceDeleteFailureEventData
	TypeResourceDeleteSuccessEventData                            Type = "Microsoft.Resources.ResourceDeleteSuccess"                         // maps to ResourceDeleteSuccessEventData
	TypeResourceNotificationsHealthResourcesAnnotatedEventData    Type = "Microsoft.ResourceNotifications.HealthResources.ResourceAnnotated" // maps to ResourceNotificationsHealthResourcesAnnotatedEventData
	TypeResourceNotificationsResourceManagementDeletedEventData   Type = "Microsoft.ResourceNotifications.Resources.Deleted"                 // maps to ResourceNotificationsResourceManagementDeletedEventData
	TypeResourceWriteCancelEventData                              Type = "Microsoft.Resources.ResourceWriteCancel"                           // maps to ResourceWriteCancelEventData
	TypeResourceWriteFailureEventData                             Type = "Microsoft.Resources.ResourceWriteFailure"                          // maps to ResourceWriteFailureEventData
	TypeResourceWriteSuccessEventData                             Type = "Microsoft.Resources.ResourceWriteSuccess"                          // maps to ResourceWriteSuccessEventData
	TypeServiceBusActiveMessagesAvailableWithNoListenersEventData Type = "Microsoft.ServiceBus.ActiveMessagesAvailableWithNoListeners"       // maps to ServiceBusActiveMessagesAvailableWithNoListenersEventData
	TypeSignalRServiceClientConnectionConnectedEventData          Type = "Microsoft.SignalRService.ClientConnectionConnected"                // maps to SignalRServiceClientConnectionConnectedEventData
	TypeSignalRServiceClientConnectionDisconnectedEventData       Type = "Microsoft.SignalRService.ClientConnectionDisconnected"             // maps to SignalRServiceClientConnectionDisconnectedEventData
	TypeStorageAsyncOperationInitiatedEventData                   Type = "Microsoft.Storage.AsyncOperationInitiated"                         // maps to StorageAsyncOperationInitiatedEventData
	TypeStorageBlobCreatedEventData                               Type = "Microsoft.Storage.BlobCreated event."                              // maps to StorageBlobCreatedEventData
	TypeStorageBlobDeletedEventData                               Type = "Microsoft.Storage.BlobDeleted event."                              // maps to StorageBlobDeletedEventData
	TypeStorageBlobRenamedEventData                               Type = "Microsoft.Storage.BlobRenamed event."                              // maps to StorageBlobRenamedEventData
	TypeStorageBlobTierChangedEventData                           Type = "Microsoft.Storage.BlobTierChanged"                                 // maps to StorageBlobTierChangedEventData
	TypeStorageDirectoryCreatedEventData                          Type = "Microsoft.Storage.DirectoryCreated"                                // maps to StorageDirectoryCreatedEventData
	TypeStorageDirectoryDeletedEventData                          Type = "Microsoft.Storage.DirectoryDeleted"                                // maps to StorageDirectoryDeletedEventData
	TypeStorageDirectoryRenamedEventData                          Type = "Microsoft.Storage.DirectoryRenamed"                                // maps to StorageDirectoryRenamedEventData
	TypeStorageLifecyclePolicyCompletedEventData                  Type = "Microsoft.Storage.LifecyclePolicyCompleted"                        // maps to StorageLifecyclePolicyCompletedEventData
	TypeWebAppServicePlanUpdatedEventData                         Type = "Microsoft.Web.AppServicePlanUpdated"                               // maps to WebAppServicePlanUpdatedEventData
	TypeWebAppUpdatedEventData                                    Type = "Microsoft.Web.AppUpdated event."                                   // maps to WebAppUpdatedEventData
	TypeWebBackupOperationCompletedEventData                      Type = "Microsoft.Web.BackupOperationCompleted"                            // maps to WebBackupOperationCompletedEventData
	TypeWebBackupOperationFailedEventData                         Type = "Microsoft.Web.BackupOperationFailed"                               // maps to WebBackupOperationFailedEventData
	TypeWebBackupOperationStartedEventData                        Type = "Microsoft.Web.BackupOperationStarted"                              // maps to WebBackupOperationStartedEventData
	TypeWebRestoreOperationCompletedEventData                     Type = "Microsoft.Web.RestoreOperationCompleted"                           // maps to WebRestoreOperationCompletedEventData
	TypeWebRestoreOperationFailedEventData                        Type = "Microsoft.Web.RestoreOperationFailed"                              // maps to WebRestoreOperationFailedEventData
	TypeWebRestoreOperationStartedEventData                       Type = "Microsoft.Web.RestoreOperationStarted"                             // maps to WebRestoreOperationStartedEventData
	TypeWebSlotSwapCompletedEventData                             Type = "Microsoft.Web.SlotSwapCompleted"                                   // maps to WebSlotSwapCompletedEventData
	TypeWebSlotSwapFailedEventData                                Type = "Microsoft.Web.SlotSwapFailed event."                               // maps to WebSlotSwapFailedEventData
	TypeWebSlotSwapStartedEventData                               Type = "Microsoft.Web.SlotSwapStarted event."                              // maps to WebSlotSwapStartedEventData
	TypeWebSlotSwapWithPreviewCancelledEventData                  Type = "Microsoft.Web.SlotSwapWithPreviewCancelled"                        // maps to WebSlotSwapWithPreviewCancelledEventData
	TypeWebSlotSwapWithPreviewStartedEventData                    Type = "Microsoft.Web.SlotSwapWithPreviewStarted"                          // maps to WebSlotSwapWithPreviewStartedEventData
)
